name: Keep Redis Active

on:
  schedule:
    - cron: '* * * * *'  # Runs every Sunday at midnight UTC

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Set Redis Key with TTL
        run: |
          curl -X POST "https://proud-colt-52684.upstash.io" \
          -H "Authorization: Bearer ${{ secrets.UPSTASH_REDIS_TOKEN }}" \
          -d "SET test active EX 60"
